### ISSUE TITLE
prefers-color-scheme locked to "light"

### ISSUE THREAD

**Issue by Carlgo11** [Marcel1202/HTMLWallpaper#18]
Hi,
not really sure what underlying program you're using and if the issue lays there instead of with HTMLWallpaper but when trying to render a webpage that uses the CSS media query `prefers-color-scheme`, "light" is always picked regardless of what the OS is set to or if there's a default option or not.

Simple CSS code to reproduce the issue in:
```CSS
body {
  background-color: red;
}

@media screen and (prefers-color-scheme: light){
  body {
    background-color: white;
  }
}

@media screen and (prefers-color-scheme: dark){
  body {
    background-color: black;
  }
}
```
